pub mod observer;
pub mod sprite;
pub mod imgload;
pub mod player;
pub mod npc;
pub mod input;
pub mod gameobject;
pub mod tile;
//pub mod tilemap;
pub mod collision;
pub mod game;
pub mod background;
pub mod platform;
pub mod desktopplatform;
pub mod talkbubble;
pub mod viewport;

extern crate piston;
extern crate graphics;
extern crate opengl_graphics;
extern crate sdl2_window;
extern crate image as im;